#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Apr  1 10:45:43 2022

@author: sjcet
"""
import numpy as np
x = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(x)
print("Display all elements excluding the first row:")
print(x[1:])


print("Display 3rd and 4th element of 1 st row:")
print(x[0,2])
print(x[0,3])